
source "https://rubygems.org"

gem "utopia", "~> 2.9"

gem "rake"
gem "bundler"

gem 'async-websocket'

gem "rack-freeze", "~> 1.2"

group :development do
	# For `rake server`:
	gem "guard-falcon", require: false
	gem 'guard-rspec', require: false
	
	# For `rake console`:
	gem "pry"
	gem "rack-test"
	
	# For `rspec` testing:
	gem "rspec"
	gem "simplecov"
	
	# For testing:
	gem 'async-rspec'
end
